[package]
name = "rlox"
version = "0.1.0"
edition = "2024"

[dependencies]
rlox-report = { path = "../rlox-report" }
rlox-lexer = { path = "../rlox-lexer" }
anyhow = "1"
derive_more = { version = "2", features = ["from", "constructor"] }
slotmap = "1"
thiserror = "2"
