[package]
name = "rlox"
version = "0.1.0"
edition = "2024"

[dependencies]
rlox-report = { path = "../rlox-report" }
rlox-tree-walk = { path = "../rlox-tree-walk" }
thiserror = "2"
anyhow = "1"
